package:
  name: wp-cli
  version: 2.12.0
  epoch: 0
  description: WP-CLI - command-line interface for WordPress
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - php
      - php-8.4-phar
      - php-8.4-curl
      - php-8.4-zip
      - php-8.4-xml
      - php-mbstring
      - bash

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/wp-cli/wp-cli/releases/download/v${{package.version}}/wp-cli-${{package.version}}.phar
      expected-sha256: ce34ddd838f7351d6759068d09793f26755463b4a4610a5a5c0a97b68220d85c
      extract: false

  - runs: |
      mkdir -p "${{targets.destdir}}/usr/local/bin"
      mv wp-cli-${{package.version}}.phar "${{targets.destdir}}/usr/local/bin/wp"
      chmod +x "${{targets.destdir}}/usr/local/bin/wp"

update:
  enabled: true
  github:
    identifier: wp-cli/wp-cli
    strip-prefix: v

test:
  pipeline:
    - runs: |
        wp --version
