package:
  name: wordpress
  version: "6.9.4"
  epoch: 2
  description: "The Open Source Publishing Platform"
  copyright:
    - license: GPL-2.0-only
  dependencies:
    runtime:
      - php-8.4
      - php-8.4-dom
      - php-8.4-xml
      - php-8.4-xmlreader

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle
      - wget

pipeline:
  - runs: |
      mkdir -p "${{targets.destdir}}/var/www/html"
      wget -q https://wordpress.org/wordpress-${{package.version}}.tar.gz
      wget -q https://wordpress.org/wordpress-${{package.version}}.tar.gz.sha1
      echo "$(cat wordpress-${{package.version}}.tar.gz.sha1)  wordpress-${{package.version}}.tar.gz" | sha1sum -c -
      tar xzf wordpress-${{package.version}}.tar.gz --strip-components=1 -C "${{targets.destdir}}/var/www/html"
      rm wordpress-${{package.version}}.tar.gz wordpress-${{package.version}}.tar.gz.sha1
      cp docker-entrypoint.sh "${{targets.destdir}}/var/www/html" || true
      cp wp-config-docker.php "${{targets.destdir}}/var/www/html" || true

subpackages:
  - name: ${{package.name}}-oci-entrypoint
    description: Entrypoint for configuring WordPress in OCI containers
    dependencies:
      runtime:
        - bash
        - busybox
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/local/bin/
          cp docker-entrypoint.sh ${{targets.subpkgdir}}/usr/local/bin/
          chmod +x ${{targets.subpkgdir}}/usr/local/bin/docker-entrypoint.sh
    test:
      pipeline:
        - uses: test/tw/byproductpackage
        - uses: test/tw/shell-syntax-check
          with:
            files: /usr/local/bin/docker-entrypoint.sh

test:
  environment:
    contents:
      packages:
        - wordpress-oci-entrypoint
        - php-fpm
        - shadow
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wolfi
      WORDPRESS_DB_PASSWORD: wolfi
  pipeline:
    - name: Run Entrypoint Script
      runs: |
        useradd -U nonroot
        mkdir -p /var/www/html && cd /var/www/html || exit
        timeout 5s /usr/local/bin/docker-entrypoint.sh php-fpm
    - name: Check Configuration
      runs: |
        test -f /var/www/html/wp-config.php
        test "$WORDPRESS_DB_NAME" = "wordpress"

update:
  enabled: true
  release-monitor:
    identifier: 4099
