package:
  name: healthcheck-sql
  version: "1.0.0"
  epoch: 0
  description: healthcheck via sql for distroless image
  copyright:
    - license: MIT

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - go-1.26

pipeline:
  - uses: go/build
    with:
      output: healthcheck-sql
      packages: .
      go-package: go-1.26
